/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Abstract]
(
[SurveyNum] [int] NOT NULL,
[County] [int] NOT NULL,
[SurveyName] [varchar] (30) NULL,
[PatentNo] [varchar] (10) NULL,
[PatentDate] [datetime] NULL,
[Acres] [int] NULL,
[Notes] [varchar] (60) NULL
)
GO
ALTER TABLE [dbo].[Abstract] ADD CONSTRAINT [PK_Abstract] PRIMARY KEY CLUSTERED ([SurveyNum], [County])
GO
